# Generated by Django 3.0.6 on 2020-07-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cemail', models.CharField(max_length=200)),
                ('adate', models.DateField(max_length=20)),
                ('alat', models.CharField(max_length=20)),
                ('alon', models.CharField(max_length=20)),
                ('anear', models.CharField(max_length=50)),
                ('aurl', models.CharField(max_length=255)),
                ('alod', models.IntegerField(max_length=5)),
                ('aoption', models.IntegerField(max_length=5)),
                ('astatus', models.IntegerField(max_length=5)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
    ]
